[cursor]
style.shape = "Block"
style.blinking = "On"

[font]
size = 13.0
normal = { family = "Monaspace Neon", style = "Regular" }

[general]
import = [
   "~/dotfiles/alacritty/themes/gruvbox_dark.toml"
]

[keyboard]
bindings = [
   { key = "Return", mods = "Alt|Shift", action = "SpawnNewInstance" }
]

[terminal]
shell = "bash"
