[cursor]
style.shape = "Block"
style.blinking = "On"

[font]
size = 11.0
normal = { family = "Monaspace Neon", style = "Regular" }

[general]
import = [
	"~/dotfiles/alacritty/themes/gruvbox_dark.toml"
]

[terminal]
shell = "bash"
